### ISSUE TITLE
Authentication credentials were missing or incorrect

### ISSUE THREAD

**Issue by pawelcala** [itog/Twitter4j-android-Sample#2]
I'm getting this kind of error and i don't know how to handle it.

04-16 11:10:09.868: W/System.err(31837): 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.

04-16 11:10:09.868: W/System.err(31837): <?xml version="1.0" encoding="UTF-8"?>
04-16 11:10:09.868: W/System.err(31837): <hash>
04-16 11:10:09.868: W/System.err(31837):   <error>Desktop applications only support the oauth_callback value 'oob'</error>
04-16 11:10:09.868: W/System.err(31837):   <request>/oauth/request_token</request>
04-16 11:10:09.868: W/System.err(31837): </hash>

I had default oauth callback, then i set it to custom one http://www.sample.com ( did also modified activity intent filter ).

**Comment by UnsafePointer** [comment]
I'm having this one too, could you fix this?
